CONTIKI_PROJECT = smartplug

all: $(CONTIKI_PROJECT)

# Do not try to build on Sky because of code size limitation
# PLATFORMS_EXCLUDE = sky z1

#Da terminare...
CONTIKI = ../../contiki-ng

include $(CONTIKI)/Makefile.include